In [2]:
import pandas as pd
import numpy as np

In [3]:
# Read in rock.csv as a data frame
df = pd.read_csv("../../assets/datasets/rock.csv")

In [4]:
# The simplest pivot table must have a dataframe and an 
# index . Let’s use the ARTIST CLEAN as our index.
pd.pivot_table(df, index=['ARTIST CLEAN'])

                                F*G  First?  PlayCount     Year?
ARTIST CLEAN
.38 Special               46.250000     1.0  47.000000  0.750000
10cc                       1.000000     1.0   1.000000  1.000000
3 Doors Down               6.666667     1.0   6.666667  1.000000
4 Non Blondes              3.000000     1.0   3.000000  1.000000
AC/DC                     26.275862     1.0  29.862069  0.689655
Ace                        1.000000     1.0   1.000000  1.000000
Adelitas Way               4.000000     1.0   4.000000  1.000000
Aerosmith                 23.645161     1.0  26.225806  0.806452
Alanis Morissette          3.500000     1.0   3.500000  1.000000
Alannah Myles              1.000000     1.0   1.000000  1.000000
Aldo Nova                  0.000000     1.0   4.000000  0.000000
Alice Cooper              14.200000     1.0  14.400000  0.800000
Alice In Chains            3.666667     1.0   3.666667  1.000000
Allman Brothers Band       6.538462     1.0   7.384615  0.769231
America                   15.333333     1.0  15.333333  1.000000
Animals II                 1.000000     1.0   1.000000  1.000000
Ann Wilson                 0.000000     1.0   2.000000  0.000000
April Wine                 0.000000     1.0   1.000000  0.000000
Argent                    11.000000     1.0  11.000000  1.000000
Arlo Guthrie               0.000000     1.0   1.000000  0.000000
Artful Dodger              0.000000     1.0   1.000000  0.000000
Asia                      20.000000     1.0  20.000000  1.000000
Atlanta Rhythm Section     0.500000     1.0   1.000000  0.500000
Audioslave                 1.000000     1.0   1.000000  1.000000
Autograph                 10.500000     1.0  11.000000  0.500000
Axe                        0.000000     1.0   1.000000  0.000000
Bachman-Turner Overdrive  30.250000     1.0  31.500000  0.750000
Bad Company               17.214286     1.0  40.500000  0.357143
Bad English                1.000000     1.0   1.000000  1.000000
Badfinger                  2.000000     1.0   2.000000  1.000000
...                             ...     ...        ...       ...
Trapeze                    0.000000     1.0   1.000000  0.000000
Triumph                    0.200000     1.0  17.600000  0.200000
Turtles                    1.000000     1.0   1.000000  1.000000
Twisted Sister            23.000000     1.0  23.000000  1.000000
U2                        23.368421     1.0  23.368421  1.000000
UB40                       2.000000     1.0   2.000000  1.000000
UFO                        0.500000     1.0  10.000000  0.500000
Uriah Heep                 1.000000     1.0   2.333333  0.666667
Van Halen                 23.977273     1.0  28.250000  0.613636
Van Morrison               7.700000     1.0   8.100000  0.600000
Violent Femmes             1.000000     1.0   1.000000  1.000000
Vixen                      0.000000     1.0   2.000000  0.000000
War                       21.750000     1.0  21.750000  1.000000
Warrant                    3.000000     1.0   3.500000  0.500000
Warren Zevon              27.500000     1.0  27.500000  1.000000
Weezer                     2.000000     1.0   2.000000  1.000000
Wet Willie                 0.000000     1.0   2.000000  0.000000
White Lion                 0.000000     1.0   1.000000  0.000000
Whitesnake                15.833333     1.0  19.166667  0.666667
Why Not                    0.000000     1.0   5.000000  0.000000
Wild Cherry                4.000000     1.0   4.000000  1.000000
Wildlife                   0.000000     1.0  13.500000  0.000000
Winger                     0.000000     1.0   1.333333  0.000000
Wishbone Ash               1.000000     1.0   1.000000  1.000000
Y&T                        0.000000     1.0   4.000000  0.000000
Yes                       23.200000     1.0  23.700000  0.900000
ZZ Top                    30.318182     1.0  32.363636  0.681818
Zebra                      0.000000     1.0   1.500000  0.000000
Zombies                   14.000000     1.0  14.000000  1.000000
a-ha                       1.000000     1.0   1.000000  1.000000

[475 rows x 4 columns]

In [3]:
# How about indexing on multiple values. Let's look at the 
# data by ARTIST CLEAN and Release Year next.

In [4]:
# What we really want to take a look at next is PlayCount. So, 
# the F*G, First?, and Year? columns aren’t useful. Let’s 
# remove them and explicitly define the 'PlayCount' column by 
# using the values field.

In [5]:
# The 'PlayCount' column automatically averages the data.  
# We can do a count or a sum by using aggfunc and np.sum.